name: Cypress Tests

on:
  push:
    branches:
      - main   # Executar em push na branch 'main'
  pull_request:
    branches:
      - main   # Executar em pull request para a branch 'main'

jobs:
  test:
    runs-on: ubuntu-latest   # Define o ambiente de execução como Ubuntu

    steps:
      # Etapa 1: Verifica o código do repositório
      - name: Check out code
        uses: actions/checkout@v2

      # Etapa 2: Configura o Node.js (versão 14, ou a que você usa no projeto)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Etapa 3: Instalar as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Etapa 4: Rodar os testes Cypress
      - name: Run Cypress tests
        run: npx cypress run --headless --no-exit  # Rodar Cypress no modo headless
        env:
          API_URL: 'https://api.autoboxoffice.app/v1/'   # URL da API para os testes

      # Etapa 5: (Opcional) Fazer upload de artefatos, como relatórios de testes
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-test-results
          path: cypress/results
