name: Cypress End-to-End Tests

on:
  push:
    branches:
      - main  # Executa os testes ao fazer push na branch main
  pull_request:
    branches:
      - main  # Executa os testes em PRs para a branch main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04  # Define o sistema operacional do runner

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Atualizado para Node.js 18, mais estável

      - name: Instalar dependências
        run: npm ci  # Usa `npm ci` para instalação mais rápida e confiável

      - name: Definir permissões para pastas
        run: sudo chown -R $USER:$USER ~/.cache/Cypress

      - name: Executar testes Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome  # Usa o Chrome ao invés do Electron
          headless: true   # Executa os testes sem interface gráfica
          config: viewportWidth=1920 viewportHeight=1080 video=true  # Garante resolução correta
          record: false  # Defina como 'true' se quiser registrar no Cypress Dashboard
        env:
          CYPRESS_BASE_URL: "https://testes.autoforce.com.br/dealer-bmw-desafio"
          CYPRESS_API_URL: "https://api.autoboxoffice.app/v1/"

      - name: Upload de vídeos e screenshots em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4  # Atualizando para a versão v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
